name: Executar deploy para o GithubPages
on:
    push:
        branches:
            - develop

jobs:
    deploy:
        name: Deployando a aplicação
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Criar ambiente do node
              uses: actions/setup-node@v1
              with: 
                node-version: 10.x
            - name: Instalar dependências e executar o script de build
              run: |
                npm install i
                npm run build
            - name: Deploy do build
              uses: s0/git-publish-subdir-action@develop
              env:
                REPO: self
                BRANCH: master
                FOLDER: dist
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}